services:
  rabbitmq:
    image: rabbitmq_curl
    build:
      dockerfile: ./rabbitmq.dockerfile
    hostname: rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"] #["rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - RABBITMQ_DEFAULT_USER=#${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=#${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      eq_inform_net:
        ipv4_address: 172.20.0.4
  admin:
    container_name: python_web_admin
    image: python_earthquake_inform
    build: 
      context: .
    ports:
      - 5000:5000
    env_file: "docker.env"
    command: "web_admin"
    volumes:
      - ./logs:/opt/earthquake/logs
      - ./instance:/opt/earthquake/instance
    networks:
      eq_inform_net:
        ipv4_address: 172.20.0.2
  bot:
    container_name: python_bot_consumer
    image: python_earthquake_inform
    build: 
      context: .
    env_file: "docker.env"
    command: "bot"
    volumes:
      - ./logs:/opt/earthquake/logs
      - ./instance:/opt/earthquake/instance
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      eq_inform_net:
        ipv4_address: 172.20.0.3

networks:
  eq_inform_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1