services:
  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=#${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=#${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
    ports:
      - 15672:15672
      - 5672:5672
